In [1]:
#imabalanced Datast: is a dataset with an unequal class distribution

In [9]:
import numpy as np
import pandas as pd

In [10]:
credit_data = pd.read_csv(r"C:\Users\Emmanuel\Downloads\credit_data.csv")

In [11]:
credit_data.head()

   Time        V1        V2        V3  ...       V27       V28  Amount  Class
0   0.0 -1.359807 -0.072781  2.536347  ...  0.133558 -0.021053  149.62      0
1   0.0  1.191857  0.266151  0.166480  ... -0.008983  0.014724    2.69      0
2   1.0 -1.358354 -1.340163  1.773209  ... -0.055353 -0.059752  378.66      0
3   1.0 -0.966272 -0.185226  1.792993  ...  0.062723  0.061458  123.50      0
4   2.0 -1.158233  0.877737  1.548718  ...  0.219422  0.215153   69.99      0

[5 rows x 31 columns]

In [6]:
credit_data.shape

(284807, 31)

In [7]:
credit_data.Class.value_counts()

Class
0    284315
1       492
Name: count, dtype: int64

In [9]:
credit_data.tail()

            Time         V1         V2  ...       V28  Amount  Class
284802  172786.0 -11.881118  10.071785  ...  0.823731    0.77      0
284803  172787.0  -0.732789  -0.055080  ... -0.053527   24.79      0
284804  172788.0   1.919565  -0.301254  ... -0.026561   67.88      0
284805  172788.0  -0.240440   0.530483  ...  0.104533   10.00      0
284806  172792.0  -0.533413  -0.189733  ...  0.013649  217.00      0

[5 rows x 31 columns]

In [10]:
credit_data.isnull().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       0
V15       0
V16       0
V17       0
V18       0
V19       0
V20       0
V21       0
V22       0
V23       0
V24       0
V25       0
V26       0
V27       0
V28       0
Amount    0
Class     0
dtype: int64

In [11]:
#This dataset is highly imbalanced
# 0 represent legit transactions and 1 represent fraudulent transactions

In [ ]:
#separating the legit and fraudulent transaction 
legit = credit_data[credit_data.Class == 0]
fraud = credit_data[credit_data.Class == 1]

In [15]:
print(legit.shape)
print(fraud.shape)

(284315, 31)
(492, 31)

In [ ]:
#There are several ways of handling imbalanced datasets. One way is Under-sampling 
#Under-sampling is done by building a sample dataset containing similar distribution of legit and fradulent transaction

In [ ]:
#Now since we have 492 fraud data, our new under-sampling legit data must be similar or equal to 492 
legit_sample = legit.sample(n=492)

In [ ]:
#concatenate the two dataframes
new_dataset = pd.concat([legit_sample, fraud], axis=0)

In [ ]:
new_dataset.head()

            Time         V1        V2  ...       V28  Amount  Class
105081   69354.0   1.138908 -0.383067  ...  0.051830   66.26      0
142677   84873.0 -10.886061  8.888982  ...  0.591589    6.15      0
206207  136114.0   2.062808 -0.108490  ... -0.061827    0.89      0
181353  124940.0   1.948766 -0.674714  ... -0.054407   45.00      0
119291   75396.0  -0.911506  0.139670  ...  0.017952    8.60      0

[5 rows x 31 columns]

In [ ]:
new_dataset.tail()

            Time        V1        V2  ...       V28  Amount  Class
279863  169142.0 -1.927883  1.125653  ...  0.147968  390.00      1
280143  169347.0  1.378559  1.289381  ...  0.186637    0.76      1
280149  169351.0 -0.676143  1.126366  ...  0.194361   77.89      1
281144  169966.0 -3.113832  0.585864  ... -0.253700  245.00      1
281674  170348.0  1.991976  0.158476  ... -0.015309   42.53      1

[5 rows x 31 columns]

In [ ]:
new_dataset.Class.value_counts()

Class
0    492
1    492
Name: count, dtype: int64

In [12]:
#Oversampling 
from sklearn.utils import resample

In [13]:
#separating the legit and fraudulent transaction 
Not_fraud = credit_data[credit_data.Class == 0]
Fraud = credit_data[credit_data.Class == 1]

In [15]:
fraud_oversampled = resample(
    Fraud,
    n_samples=len(Not_fraud),
    random_state = 42
)

In [17]:
New_dataset = pd.concat([Not_fraud, fraud_oversampled], axis = 0)

In [18]:
Not_fraud.shape

(284315, 31)

In [19]:
fraud_oversampled.shape

(284315, 31)

In [20]:
print(New_dataset['Class'].value_counts())

Class
0    284315
1    284315
Name: count, dtype: int64

In [21]:
New_dataset.head()

   Time        V1        V2        V3  ...       V27       V28  Amount  Class
0   0.0 -1.359807 -0.072781  2.536347  ...  0.133558 -0.021053  149.62      0
1   0.0  1.191857  0.266151  0.166480  ... -0.008983  0.014724    2.69      0
2   1.0 -1.358354 -1.340163  1.773209  ... -0.055353 -0.059752  378.66      0
3   1.0 -0.966272 -0.185226  1.792993  ...  0.062723  0.061458  123.50      0
4   2.0 -1.158233  0.877737  1.548718  ...  0.219422  0.215153   69.99      0

[5 rows x 31 columns]

In [22]:
New_dataset.tail()

            Time         V1         V2  ...       V28  Amount  Class
229712  146022.0   0.908637   2.849024  ...  0.360224    1.18      1
15781    27219.0 -25.266355  14.323254  ...  0.414656   99.99      1
251881  155542.0   1.868226   1.363077  ...  0.017258    3.14      1
154234  100924.0 -23.984747  16.697832  ... -0.334561    1.00      1
281144  169966.0  -3.113832   0.585864  ... -0.253700  245.00      1

[5 rows x 31 columns]

In [23]:
#SMOTE (Synthetic Minority Oversampling Technique)
from imblearn.over_sampling import SMOTE

In [25]:
X = credit_data.drop(columns='Class', axis = 1)
Y = credit_data['Class']

smote = SMOTE(random_state=42)

In [27]:
print("Before SMOTE:", X.shape, Y.shape)

Before SMOTE: (284807, 30) (284807,)

In [26]:
X_resampled, Y_resampled = smote.fit_resample(X, Y)

In [28]:
print("After SMOTE:", X_resampled.shape, Y_resampled.shape)

After SMOTE: (568630, 30) (568630,)

In [29]:
print(Y_resampled.value_counts())

Class
0    284315
1    284315
Name: count, dtype: int64