In [137]:
#   Diabetes Prediction using KNN Classifier

In [138]:
#   Importing the libraries

import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [139]:
#   loading the dataset
diabetes_data = pd.read_csv(r"C:\Users\Emmanuel\Desktop\Dataset\diabetes.csv")

In [140]:
#   printing the first 5 rows of the dataset
diabetes_data.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [141]:
#   number of rows and columns in the dataset
diabetes_data.shape

(768, 9)

In [142]:
#   getting the statistical measures of the data
diabetes_data.describe()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
count,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000
mean,3.845052,120.894531,69.105469,20.536458,79.799479,31.992578,0.471876,33.240885,0.348958
std,3.369578,31.972618,19.355807,15.952218,115.244002,7.884160,0.331329,11.760232,0.476951
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.078000,21.000000,0.000000
25%,1.000000,99.000000,62.000000,0.000000,0.000000,27.300000,0.243750,24.000000,0.000000
50%,3.000000,117.000000,72.000000,23.000000,30.500000,32.000000,0.372500,29.000000,0.000000
75%,6.000000,140.250000,80.000000,32.000000,127.250000,36.600000,0.626250,41.000000,1.000000
max,17.000000,199.000000,122.000000,99.000000,846.000000,67.100000,2.420000,81.000000,1.000000

In [143]:
#   separating the features and target
X = diabetes_data.drop(columns='Outcome', axis=1)
y = diabetes_data['Outcome']

In [144]:
#   converting the data to numpy array
X = X.to_numpy()
Y = y.to_numpy()

In [145]:
print(X)
print(Y)

[[  6.    148.     72.    ...  33.6     0.627  50.   ]
 [  1.     85.     66.    ...  26.6     0.351  31.   ]
 [  8.    183.     64.    ...  23.3     0.672  32.   ]
 ...
 [  5.    121.     72.    ...  26.2     0.245  30.   ]
 [  1.    126.     60.    ...  30.1     0.349  47.   ]
 [  1.     93.     70.    ...  30.4     0.315  23.   ]]
[1 0 1 0 1 0 1 0 1 1 0 1 0 1 1 1 1 1 0 1 0 0 1 1 1 1 1 0 0 0 0 1 0 0 0 0 0
 1 1 1 0 0 0 1 0 1 0 0 1 0 0 0 0 1 0 0 1 0 0 0 0 1 0 0 1 0 1 0 0 0 1 0 1 0
 0 0 0 0 1 0 0 0 0 0 1 0 0 0 1 0 0 0 0 1 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 1 1
 1 0 0 1 1 1 0 0 0 1 0 0 0 1 1 0 0 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0
 0 0 0 0 1 0 1 1 0 0 0 1 0 0 0 0 1 1 0 0 0 0 1 1 0 0 0 1 0 1 0 1 0 0 0 0 0
 1 1 1 1 1 0 0 1 1 0 1 0 1 1 1 0 0 0 0 0 0 1 1 0 1 0 0 0 1 1 1 1 0 1 1 1 1
 0 0 0 0 0 1 0 0 1 1 0 0 0 1 1 1 1 0 0 0 1 1 0 1 0 0 0 0 0 0 0 0 1 1 0 0 0
 1 0 1 0 0 1 0 1 0 0 1 1 0 0 0 0 0 1 0 0 0 1 0 0 1 1 0 0 1 0 0 0 1 1 1 0 0
 1 0 1 0 1 1 0 1 0 0 1 0 1 1 0 0 1 0 1 0 0 1 0 1 0 1 1 1 0 0 1 0 1 0 0 0 1
 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 1 1 0 1 1 0 0 1 0 0 1 0 0 1
 1 0 0 0 0 1 0 0 1 0 0 0 0 0 0 0 1 1 1 0 0 1 0 0 1 0 0 1 0 1 1 0 1 0 1 0 1
 0 1 1 0 0 0 0 1 1 0 1 0 1 0 0 0 0 1 1 0 1 0 1 0 0 0 0 0 1 0 0 0 0 1 0 0 1
 1 1 0 0 1 0 0 1 0 0 0 1 0 0 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 1 0 0 0 1
 0 0 0 1 1 0 0 0 0 0 0 0 1 0 0 0 0 1 0 0 0 1 0 0 0 1 0 0 0 1 0 0 0 0 1 1 0
 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 1 1 1 1 0 0 1 1 0 0 0 0 0 0 0 0
 0 0 0 0 0 1 1 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 1 0 1 1 0 0 0 1 0 1 0 1 0 1 0
 1 0 0 1 0 0 1 0 0 0 0 1 1 0 1 0 0 0 0 1 1 0 1 0 0 0 1 1 0 0 0 0 0 0 0 0 0
 0 1 0 0 0 0 1 0 0 1 0 0 0 1 0 0 0 1 1 1 0 0 0 0 0 0 1 0 0 0 1 0 1 1 1 1 0
 1 1 0 0 0 0 0 0 0 1 1 0 1 0 0 1 0 1 0 0 0 0 0 1 0 1 0 1 0 1 1 0 0 0 0 1 1
 0 0 0 1 0 1 1 0 0 1 0 0 1 1 0 0 1 0 0 1 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 1
 1 0 0 1 0 0 1 0 1 1 1 0 0 1 1 1 0 1 0 1 0 1 0 0 0 0 1 0]

In [146]:
#   train test split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, stratify=Y, random_state=2)

In [147]:
print(X.shape, X_train.shape, X_test.shape)

(768, 8) (614, 8) (154, 8)

In [148]:
print(X_train)

[[0.00e+00 1.19e+02 0.00e+00 ... 3.24e+01 1.41e-01 2.40e+01]
 [6.00e+00 1.05e+02 7.00e+01 ... 3.08e+01 1.22e-01 3.70e+01]
 [1.00e+00 1.89e+02 6.00e+01 ... 3.01e+01 3.98e-01 5.90e+01]
 ...
 [1.10e+01 8.50e+01 7.40e+01 ... 3.01e+01 3.00e-01 3.50e+01]
 [4.00e+00 1.12e+02 7.80e+01 ... 3.94e+01 2.36e-01 3.80e+01]
 [0.00e+00 8.60e+01 6.80e+01 ... 3.58e+01 2.38e-01 2.50e+01]]

In [149]:
X_train = np.insert(X_train, 8, Y_train, axis=1)

In [150]:
print(X_train)

[[0.00e+00 1.19e+02 0.00e+00 ... 1.41e-01 2.40e+01 1.00e+00]
 [6.00e+00 1.05e+02 7.00e+01 ... 1.22e-01 3.70e+01 0.00e+00]
 [1.00e+00 1.89e+02 6.00e+01 ... 3.98e-01 5.90e+01 1.00e+00]
 ...
 [1.10e+01 8.50e+01 7.40e+01 ... 3.00e-01 3.50e+01 0.00e+00]
 [4.00e+00 1.12e+02 7.80e+01 ... 2.36e-01 3.80e+01 0.00e+00]
 [0.00e+00 8.60e+01 6.80e+01 ... 2.38e-01 2.50e+01 0.00e+00]]

In [151]:
X_train.shape

(614, 9)

In [152]:
#   X_train ---> training data with features and target
#   X_test ---> testing data without target

In [153]:
#   Model Training: KNN Classifier

import numpy as np
import statistics

class KNN_Classifier():
    #   initiating the parameter 
    def __init__(self, distance_metric):

        self.distance_metric = distance_metric
    
    #   getting the distance metric
    def get_distance_metric(self, training_data_point, test_data_point):

        if (self.distance_metric == 'euclidean'):

            dist = 0

            for i in range(len(training_data_point) - 1):
                dist = dist + (training_data_point[i] - test_data_point[i])**2

            euclidean_dist = np.sqrt(dist)
            return euclidean_dist

        elif (self.distance_metric == 'manhattan'):

            dist = 0

            for i in range(len(training_data_point) - 1):
                dist = dist + abs(training_data_point[i] - test_data_point[i])

            manhattan_dist = dist
            return manhattan_dist        
    #   Getting the nearest neighbors 
    def nearest_neighbors(self, X_train, test_data, k):

        distance_list = []

        for training_data in X_train:

            distance = self.get_distance_metric(training_data, test_data)
            distance_list.append((training_data, distance))

        distance_list.sort(key=lambda x:x[1])

        neighbors_list = []

        for j in range(k):
            neighbors_list.append(distance_list[j][0])

        return neighbors_list        

    #   predict the class of new data points
    def predict(self, X_train, test_data, k):

        neighbors = self.nearest_neighbors(X_train, test_data, k)
        
        
        label = []
        for data in neighbors:
            
            label.append(data[-1])

        predicted_class = statistics.mode(label)

        return predicted_class

In [154]:
classifier = KNN_Classifier(distance_metric='euclidean')

prediction = classifier.predict(X_train, X_test[0], k=5)

In [155]:
print(X_test[0])

print(Y_test[0])

print(prediction)

[  3.    106.     72.      0.      0.     25.8     0.207  27.   ]
0
0.0

In [156]:
X_test.shape

(154, 8)

In [157]:
X_test_size = X_test.shape[0]
print(X_test_size)

154

In [158]:
y_pred = []

for i in range(X_test_size):
    prediction = classifier.predict(X_train, X_test[i], k=5)
    y_pred.append(prediction)

In [159]:
print(y_pred)

[np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(1.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(1.0), np.float64(0.0), np.float64(1.0), np.float64(0.0), np.float64(0.0), np.float64(1.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(1.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(1.0), np.float64(1.0), np.float64(1.0), np.float64(1.0), np.float64(0.0), np.float64(0.0), np.float64(1.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(1.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(1.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(1.0), np.float64(0.0), np.float64(1.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(1.0), np.float64(1.0), np.float64(0.0), np.float64(0.0), np.float64(1.0), np.float64(0.0), np.float64(1.0), np.float64(1.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(1.0), np.float64(0.0), np.float64(0.0), np.float64(1.0), np.float64(0.0), np.float64(1.0), np.float64(0.0), np.float64(1.0), np.float64(0.0), np.float64(0.0), np.float64(1.0), np.float64(0.0), np.float64(0.0), np.float64(1.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(1.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(1.0), np.float64(0.0), np.float64(0.0), np.float64(1.0), np.float64(1.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(1.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(1.0), np.float64(1.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(1.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(1.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(1.0), np.float64(0.0), np.float64(0.0), np.float64(1.0)]

In [160]:
y_true = Y_test

In [161]:
#   Model Evaluation

In [162]:
accuracy = accuracy_score(y_true, y_pred)

In [163]:
print (accuracy*100) # accuracy score in percentage

72.72727272727273

In [164]:
#   Comparing to the Standard KNN Classifier from sklearn

In [165]:
from sklearn.neighbors import KNeighborsClassifier

In [166]:
#   Separating the features and target
X = diabetes_data.drop(columns='Outcome', axis=1)
Y = diabetes_data['Outcome']

#    train test split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, stratify=Y, random_state=2)

print(X.shape, X_train.shape, X_test.shape)

(768, 8) (614, 8) (154, 8)

In [167]:
#    KNN classifier from sklearn
classifier = KNeighborsClassifier(p=2) #    p=2 for Euclidean distance, p=1 for Manhattan distance
classifier.fit(X_train, Y_train)

KNeighborsClassifier()

In [168]:
#   Model Evaluation

y_pred = classifier.predict(X_test)

accuracy = accuracy_score(Y_test, y_pred)

print (accuracy*100) # accuracy score in percentage

72.72727272727273

In [169]:
#   Using a handbuilt KNN Classifier - Mahattan distance metric

In [170]:
print(type(X_train), type(X_test), type(Y_train), type(Y_test))

<class 'pandas.core.frame.DataFrame'> <class 'pandas.core.frame.DataFrame'> <class 'pandas.core.series.Series'> <class 'pandas.core.series.Series'>

In [171]:
#   Separating the features and target
X = diabetes_data.drop(columns='Outcome', axis=1).to_numpy()
Y = diabetes_data['Outcome'].to_numpy()

#    train test split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, stratify=Y, random_state=2)

train_data = np.insert(X_train, 8, Y_train, axis=1)

print(X.shape, X_train.shape, X_test.shape)

print(set(train_data[:, -1]))

(768, 8) (614, 8) (154, 8)
{np.float64(0.0), np.float64(1.0)}

In [172]:
classifier = KNN_Classifier(distance_metric='manhattan')

prediction = classifier.predict(train_data, X_test[0], k=5)
print('X_test is:', X_test[0])

print('Y_test is:', Y_test[0])

print('Prediction is:', prediction)
X_test.shape
X_test_size = X_test.shape[0]
print('X_test_size is:', X_test_size)
y_pred = []

for i in range(X_test_size):
    prediction = classifier.predict(train_data, X_test[i], k=5)
    y_pred.append(prediction)
print('y_pred is:', y_pred)
y_true = Y_test

X_test is: [  3.    106.     72.      0.      0.     25.8     0.207  27.   ]
Y_test is: 0
Prediction is: 0.0
X_test_size is: 154

y_pred is: [np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(1.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(1.0), np.float64(0.0), np.float64(0.0), np.float64(1.0), np.float64(0.0), np.float64(0.0), np.float64(1.0), np.float64(0.0), np.float64(1.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(1.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(1.0), np.float64(0.0), np.float64(0.0), np.float64(1.0), np.float64(0.0), np.float64(0.0), np.float64(1.0), np.float64(0.0), np.float64(1.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(1.0), np.float64(0.0), np.float64(0.0), np.float64(1.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(1.0), np.float64(0.0), np.float64(1.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(1.0), np.float64(0.0), np.float64(1.0), np.float64(1.0), np.float64(0.0), np.float64(1.0), np.float64(0.0), np.float64(0.0), np.float64(1.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(1.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(1.0), np.float64(0.0), np.float64(0.0), np.float64(1.0), np.float64(0.0), np.float64(0.0), np.float64(1.0), np.float64(1.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(1.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(1.0), np.float64(0.0), np.float64(0.0), np.float64(1.0), np.float64(1.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(1.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(1.0), np.float64(1.0), np.float64(1.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(1.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(1.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(0.0), np.float64(1.0), np.float64(0.0), np.float64(0.0), np.float64(1.0)]

In [180]:
#   Model Evaluation for Manhattan distance metric
accuracy = accuracy_score(y_true, y_pred)
print (accuracy*100) # accuracy score in percentage

77.92207792207793

In [174]:
#   Comparing to the Standard KNN Classifier from sklearn - Manhattan distance metric

#   Separating the features and target
X = diabetes_data.drop(columns='Outcome', axis=1)
Y = diabetes_data['Outcome']

#    train test split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, stratify=Y, random_state=2)

print(X.shape, X_train.shape, X_test.shape)

(768, 8) (614, 8) (154, 8)

In [175]:
#    KNN classifier from sklearn
classifier = KNeighborsClassifier(p=1) #    p=2 for Euclidean distance, p=1 for Manhattan distance
classifier.fit(X_train, Y_train)
#   Model Evaluation

y_pred = classifier.predict(X_test)

accuracy = accuracy_score(Y_test, y_pred)

print (accuracy*100) # accuracy score in percentage

77.92207792207793

In [179]:
#    Confusion Matrix for sklearn KNN Classifier

In [177]:
from sklearn.metrics import confusion_matrix, classification_report
from sklearn.neighbors import KNeighborsClassifier

models = {
    'sklearn Euclidean': KNeighborsClassifier(n_neighbors=5, p=2),
    'sklearn Manhattan': KNeighborsClassifier(n_neighbors=5, p=1),
}

for name, model in models.items():
    model.fit(X_train, Y_train)
    preds = model.predict(X_test)
    print('=====', name, '=====')
    print(confusion_matrix(Y_test, preds))
    print(classification_report(Y_test, preds))

===== sklearn Euclidean =====
[[88 12]
 [30 24]]
              precision    recall  f1-score   support

           0       0.75      0.88      0.81       100
           1       0.67      0.44      0.53        54

    accuracy                           0.73       154
   macro avg       0.71      0.66      0.67       154
weighted avg       0.72      0.73      0.71       154

===== sklearn Manhattan =====
[[92  8]
 [26 28]]
              precision    recall  f1-score   support

           0       0.78      0.92      0.84       100
           1       0.78      0.52      0.62        54

    accuracy                           0.78       154
   macro avg       0.78      0.72      0.73       154
weighted avg       0.78      0.78      0.77       154

In [ ]:
#   Hand-built KNN Classifier Confusion matrix

In [178]:
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, classification_report

# fresh NumPy arrays, with names that don't clash with the sklearn cells
X_np = diabetes_data.drop(columns='Outcome', axis=1).to_numpy()
Y_np = diabetes_data['Outcome'].to_numpy()

Xtr, Xte, Ytr, Yte = train_test_split(X_np, Y_np, test_size=0.2, stratify=Y_np, random_state=2)

# handbuilt model needs the label as the last column
hand_train = np.insert(Xtr, 8, Ytr, axis=1)

for metric in ['euclidean', 'manhattan']:
    hand_knn = KNN_Classifier(distance_metric=metric)
    hand_preds = [int(hand_knn.predict(hand_train, Xte[i], k=5)) for i in range(len(Xte))]

    print('=====', 'handbuilt', metric.capitalize(), '=====')
    print(confusion_matrix(Yte, hand_preds))
    print(classification_report(Yte, hand_preds))

===== handbuilt Euclidean =====
[[88 12]
 [30 24]]
              precision    recall  f1-score   support

           0       0.75      0.88      0.81       100
           1       0.67      0.44      0.53        54

    accuracy                           0.73       154
   macro avg       0.71      0.66      0.67       154
weighted avg       0.72      0.73      0.71       154

===== handbuilt Manhattan =====
[[92  8]
 [26 28]]
              precision    recall  f1-score   support

           0       0.78      0.92      0.84       100
           1       0.78      0.52      0.62        54

    accuracy                           0.78       154
   macro avg       0.78      0.72      0.73       154
weighted avg       0.78      0.78      0.77       154